### ISSUE TITLE
Possible to work on other kim/kiss sites?

### ISSUE THREAD

**Issue by bearachute** [thorio/kaGrabber#1]
I've been messing around with the source code, for kimcartoon especially, there's a lot of the same structure however just replacing the @match doesn't seem to be enough. I can't figure out what's wrong with the code or why showing up. Removing instances of kissanime doesn't seem to be enough, I can get the links just fine.

Anyways wondering if it was _at all possible_

Thanks for the great work!

**Comment by thorio** [comment]
There are a few minor differences, but it should be fairly easy to adapt it to other sites with a similar structure. I'll try to write a working version for kimcartoon tomorrow.

**Comment by bearachute** [comment]
hey thanks it’s no biggie, there used to be one for kisscartoon back in the day, but the guy up and disappeared. i looked at your source and plugged a bit of it into kimcartoon, i have no experience going through how DOM works but i was able to get the openco (?) links using your code as a basis, i think there was one minor change i made to something. anyways just wondering!

**Comment by thorio** [comment]
I got a working version up on another repo now, not sure if I'm going to integrate it into this script yet.
[Check it out](https://github.com/thorio/kcGrabber)
