### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by alabastida** [thorio/kaGrabber#4]
Hi guys, so, I tried the link grabber with different shows and each of the servers in the link grabber dropdown but all I get is a white page and a popup with the word "undefined" on it. Sometimes i get the captcha prompt, but after that it goes to the white page and the undefined popup..

Tested it on WIndows 10, Chrome latest version with TamperMonkey.

**Comment by thorio** [comment]
I've never encountered anything like this, very strange.
Please tell me everything you can, like the show, which episode/s and server etc.

**Comment by thorio** [comment]
Closed for inactivity.
